name: run get_data.py

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: run script
        run: python get_data.py

      - name: commit files
        run: |
          git config --local user.email "<>"
          git config --local user.name "github actions bot"
          git add -A
          git diff-index --quiet HEAD || git commit -m "added data"
          git push
